/* =================================================================
   PROJETOS: usado pelo site (index.html) e pela Galeria (galeria.html).
   Toda arte colocada aqui aparece nas duas páginas.
   ================================================================= */

/* 3. Projetos: um card por projeto.
   via = empresa/agência · client = marca atendida
   images = artes (a primeira vira capa; ou use cover = "img/..." para outra capa) */
const PROJECTS = [
  { via: "End to End", client: "Avanti Palmeiras", cover: "img/b/avanti-44.jpg", images: ["img/b/avanti-2.jpg", "img/b/avanti-3.jpg", "img/b/avanti-4.jpg", "img/b/avanti-5.jpg", "img/b/avanti-6.jpg", "img/b/avanti-7.jpg", "img/b/avanti-8.jpg", "img/b/avanti-9.jpg", "img/b/avanti-10.jpg", "img/b/avanti-11.jpg", "img/b/avanti-12.jpg", "img/b/avanti-13.jpg", "img/b/avanti-14.jpg", "img/b/avanti-15.jpg", "img/b/avanti-16.jpg", "img/b/avanti-17.jpg", "img/b/avanti-18.jpg", "img/b/avanti-19.jpg", "img/b/avanti-20.jpg", "img/b/avanti-21.jpg", "img/b/avanti-22.jpg", "img/b/avanti-23.jpg", "img/b/avanti-24.jpg", "img/b/avanti-25.jpg", "img/b/avanti-26.jpg", "img/b/avanti-27.jpg", "img/b/avanti-28.jpg", "img/b/avanti-29.jpg", "img/b/avanti-30.jpg", "img/b/avanti-31.jpg", "img/b/avanti-32.jpg", "img/b/avanti-33.jpg", "img/b/avanti-34.jpg", "img/b/avanti-35.jpg", "img/b/avanti-36.jpg", "img/b/avanti-37.jpg", "img/b/avanti-38.jpg", "img/b/avanti-39.jpg", "img/b/avanti-40.jpg", "img/b/avanti-41.jpg", "img/b/avanti-42.jpg", "img/b/avanti-43.jpg", "img/b/avanti-44.jpg", "img/b/avanti-45.jpg", "img/b/avanti-46.jpg", "img/b/avanti-47.jpg", "img/b/avanti-48.jpg", "img/b/avanti-49.jpg", "img/b/avanti-50.jpg", "img/b/avanti-51.jpg"],
    text: { pt: "Peças para o programa de sócio-torcedor do Palmeiras, criadas para as campanhas e redes do Avanti.", en: "Visuals for Palmeiras' membership programme, made for Avanti campaigns and social channels." } },
  { via: "End to End", client: "Grêmio", cover: "img/proj/gremio-19.jpg", images: ["img/proj/gremio-1.jpg", "img/proj/gremio-2.jpg", "img/proj/gremio-3.jpg", "img/proj/gremio-4.jpg", "img/proj/gremio-5.jpg", "img/proj/gremio-6.jpg", "img/proj/gremio-7.jpg", "img/proj/gremio-8.jpg", "img/proj/gremio-9.jpg", "img/proj/gremio-10.jpg", "img/proj/gremio-11.jpg", "img/proj/gremio-12.jpg", "img/proj/gremio-13.jpg", "img/proj/gremio-14.jpg", "img/proj/gremio-15.jpg", "img/proj/gremio-16.jpg", "img/proj/gremio-17.jpg", "img/proj/gremio-18.jpg", "img/proj/gremio-19.jpg", "img/proj/gremio-20.jpg", "img/proj/gremio-21.jpg", "img/proj/gremio-22.jpg"],
    text: { pt: "Criação de peças para campanhas do Grêmio desenvolvidas pela End to End.", en: "Visuals for Grêmio campaigns developed by End to End." } },
  { via: "End to End", client: "Loja do Galo", cover: "img/b/lojadogalo-12.jpg", images: ["img/b/lojadogalo-1.jpg", "img/b/lojadogalo-2.jpg", "img/b/lojadogalo-3.jpg", "img/b/lojadogalo-4.jpg", "img/b/lojadogalo-5.jpg", "img/b/lojadogalo-6.jpg", "img/b/lojadogalo-7.jpg", "img/b/lojadogalo-8.jpg", "img/b/lojadogalo-9.jpg", "img/b/lojadogalo-10.jpg", "img/b/lojadogalo-11.jpg", "img/b/lojadogalo-12.jpg", "img/b/lojadogalo-13.jpg", "img/b/lojadogalo-14.jpg", "img/b/lojadogalo-15.jpg", "img/b/lojadogalo-16.jpg", "img/b/lojadogalo-17.jpg", "img/b/lojadogalo-18.jpg"],
    text: { pt: "Peças promocionais para a loja oficial do Atlético-MG.", en: "Promotional visuals for Atlético-MG's official store." } },
  { via: "Yeap Films", client: "H2 Bet", cover: "img/b/h2bet-2.jpg", images: ["img/b/h2bet-1.jpg", "img/b/h2bet-2.jpg", "img/b/h2bet-3.jpg", "img/b/h2bet-4.jpg", "img/b/h2bet-5.jpg", "img/b/h2bet-6.jpg", "img/b/h2bet-7.jpg", "img/b/h2bet-8.jpg", "img/b/h2bet-9.jpg", "img/b/h2bet-10.jpg", "img/b/h2bet-11.jpg", "img/b/h2bet-12.jpg", "img/b/h2bet-13.jpg", "img/b/h2bet-14.jpg", "img/b/h2bet-15.jpg", "img/b/h2bet-16.jpg", "img/b/h2bet-17.jpg", "img/b/h2bet-18.jpg", "img/b/h2bet-19.jpg", "img/b/h2bet-20.jpg", "img/b/h2bet-21.jpg", "img/b/h2bet-22.jpg", "img/b/h2bet-23.jpg", "img/b/h2bet-24.jpg", "img/b/h2bet-25.jpg", "img/b/h2bet-26.jpg", "img/b/h2bet-27.jpg", "img/b/h2bet-28.jpg", "img/b/h2bet-29.jpg", "img/b/h2bet-30.jpg"],
    text: { pt: "Criação visual para campanhas e conteúdos da H2 Bet.", en: "Visual design for H2 Bet campaigns and content." } },
  { via: "Yeap Films", client: "Atlético-MG", images: ["img/b/galo-h2-1.jpg", "img/b/galo-h2-2.jpg", "img/b/galo-h2-3.jpg", "img/b/galo-h2-4.jpg", "img/b/galo-h2-5.jpg", "img/b/galo-h2-6.jpg"],
    text: { pt: "Peças da H2bet como patrocinadora máster do Galo: dias de jogo, títulos e ações com a torcida.", en: "Visuals for H2bet as master sponsor of Atlético-MG: matchdays, titles and fan activations." } },
  { via: "Yeap Films", client: "Seu Bet", cover: "img/b/seubet-15.jpg", images: ["img/b/seubet-1.jpg", "img/b/seubet-2.jpg", "img/b/seubet-3.jpg", "img/b/seubet-4.jpg", "img/b/seubet-5.jpg", "img/b/seubet-6.jpg", "img/b/seubet-7.jpg", "img/b/seubet-8.jpg", "img/b/seubet-9.jpg", "img/b/seubet-10.jpg", "img/b/seubet-11.jpg", "img/b/seubet-12.jpg", "img/b/seubet-13.jpg", "img/b/seubet-14.jpg", "img/b/seubet-15.jpg", "img/b/seubet-16.jpg", "img/b/seubet-17.jpg", "img/b/seubet-18.jpg", "img/b/seubet-19.jpg", "img/b/seubet-20.jpg"],
    text: { pt: "Criação visual para campanhas e redes sociais da Seu Bet.", en: "Visual design for Seu Bet campaigns and social media." } },
  { via: "Yeap Films", client: "Luiz Henrique", images: ["img/b/luizhenrique-1.jpg"],
    text: { pt: "Peças especiais com o atacante Luiz Henrique: conquistas, Seleção Brasileira e a indicação ao FIFA The Best 2025.", en: "Special visuals featuring forward Luiz Henrique: titles, the Brazil national team and his FIFA The Best 2025 nomination." } },
  { via: "North Star Network", client: "Trivela", images: ["img/b/trivela-1.jpg", "img/b/trivela-2.jpg", "img/b/trivela-3.jpg", "img/b/trivela-4.jpg", "img/b/trivela-5.jpg", "img/b/trivela-6.jpg", "img/b/trivela-7.jpg", "img/b/trivela-8.jpg", "img/b/trivela-9.jpg", "img/b/trivela-10.jpg", "img/b/trivela-11.jpg", "img/b/trivela-12.jpg", "img/b/trivela-13.jpg", "img/b/trivela-14.jpg", "img/b/trivela-15.jpg", "img/b/trivela-16.jpg", "img/b/trivela-17.jpg", "img/b/trivela-18.jpg", "img/b/trivela-19.jpg", "img/b/trivela-20.jpg", "img/b/trivela-21.jpg", "img/b/trivela-22.jpg", "img/b/trivela-23.jpg", "img/b/trivela-24.jpg", "img/b/trivela-25.jpg", "img/b/trivela-26.jpg", "img/b/trivela-27.jpg", "img/b/trivela-28.jpg", "img/b/trivela-29.jpg", "img/b/trivela-30.jpg", "img/b/trivela-31.jpg", "img/b/trivela-32.jpg", "img/b/trivela-33.jpg", "img/b/trivela-34.jpg", "img/b/trivela-35.jpg", "img/b/trivela-36.jpg", "img/b/trivela-37.jpg", "img/b/trivela-38.jpg", "img/b/trivela-39.jpg", "img/b/trivela-40.jpg", "img/b/trivela-41.jpg", "img/b/trivela-42.jpg", "img/b/trivela-43.jpg", "img/b/trivela-44.jpg", "img/b/trivela-45.jpg", "img/b/mundial-2.jpg", "img/b/mundial-3.jpg", "img/b/mundial-4.jpg", "img/b/mundial-5.jpg", "img/b/mundial-6.jpg", "img/b/mundial-7.jpg", "img/b/mundial-8.jpg", "img/b/mundial-9.jpg", "img/b/mundial-10.jpg", "img/b/mundial-11.jpg", "img/b/mundial-12.jpg", "img/b/mundial-13.jpg", "img/b/mundial-14.jpg", "img/b/mundial-15.jpg", "img/b/mundial-16.jpg", "img/b/mundial-17.jpg", "img/b/mundial-18.jpg", "img/b/mundial-19.jpg", "img/b/mundial-20.jpg", "img/b/mundial-21.jpg", "img/b/mundial-22.jpg", "img/b/mundial-23.jpg", "img/b/mundial-24.jpg"],
    text: { pt: "Criação da identidade visual para redes e conteúdo da Trivela.", en: "Visual identity for Trivela's social media and content." } },
  { via: "North Star Network", client: "UmDois Esportes", cover: "img/b/umdois-2.jpg", images: ["img/b/umdois-1.jpg", "img/b/umdois-2.jpg", "img/b/umdois-3.jpg", "img/b/umdois-4.jpg", "img/b/umdois-5.jpg", "img/b/umdois-6.jpg", "img/b/umdois-7.jpg", "img/b/umdois-8.jpg", "img/b/umdois-9.jpg", "img/b/umdois-10.jpg", "img/b/umdois-11.jpg", "img/b/umdois-12.jpg"],
    text: { pt: "Criação de peças para o conteúdo da UmDois Esportes.", en: "Visuals for UmDois Esportes content." } },
  { via: "North Star Network", client: "PL Brasil", cover: "img/b/plbr-4.jpg", images: ["img/b/plbr-1.jpg", "img/b/plbr-2.jpg", "img/b/plbr-3.jpg", "img/b/plbr-4.jpg", "img/b/plbr-5.jpg", "img/b/plbr-6.jpg", "img/b/plbr-7.jpg", "img/b/plbr-8.jpg", "img/b/plbr-9.jpg", "img/b/plbr-10.jpg", "img/b/plbr-11.jpg", "img/b/plbr-12.jpg", "img/b/plbr-13.jpg", "img/b/plbr-14.jpg", "img/b/plbr-15.jpg", "img/b/plbr-16.jpg", "img/b/plbr-17.jpg", "img/b/plbr-18.jpg", "img/b/plbr-19.jpg", "img/b/plbr-20.jpg", "img/b/plbr-21.jpg", "img/b/plbr-22.jpg", "img/b/plbr-23.jpg", "img/b/plbr-24.jpg", "img/b/plbr-25.jpg", "img/b/plbr-26.jpg", "img/b/plbr-27.jpg", "img/b/plbr-28.jpg", "img/b/plbr-29.jpg", "img/b/plbr-30.jpg", "img/b/plbr-31.jpg"],
    text: { pt: "Artes para as redes da PL Brasil, perfil brasileiro da Premier League: clássicos, títulos, ídolos e curiosidades do futebol inglês.", en: "Artwork for PL Brasil, the Brazilian Premier League page: big matches, titles, legends and English football trivia." } },
  { via: "Sportsbet.io", client: "Flamengo", images: ["img/b/flamengo-1.jpg", "img/b/flamengo-2.jpg", "img/b/flamengo-3.jpg", "img/b/flamengo-4.jpg", "img/b/flamengo-5.jpg", "img/b/flamengo-6.jpg", "img/b/flamengo-7.jpg", "img/b/flamengo-8.jpg", "img/b/flamengo-9.jpg"],
    text: { pt: "Peças exclusivas para a ativação da parceria entre a Sportsbet.io e o Flamengo.", en: "Exclusive visuals for the partnership activation between Sportsbet.io and Flamengo." } },
  { via: "Sportsbet.io", client: "São Paulo FC", images: ["img/b/spfc-1.jpg", "img/b/spfc-2.jpg", "img/b/spfc-3.jpg", "img/b/spfc-4.jpg", "img/b/spfc-5.jpg", "img/b/spfc-6.jpg", "img/b/spfc-7.jpg", "img/b/sbsocial-2.jpg", "img/b/sbsocial-15.jpg"],
    text: { pt: "Peças exclusivas para a ativação da parceria entre a Sportsbet.io e o São Paulo FC.", en: "Exclusive visuals for the partnership activation between Sportsbet.io and São Paulo FC." } },
  { via: "Sportsbet.io", client: "Redes sociais", cover: "img/b/sbsocial-5.jpg", images: ["img/b/sbsocial-2.jpg", "img/b/sbsocial-3.jpg", "img/b/sbsocial-4.jpg", "img/b/sbsocial-5.jpg", "img/b/sbsocial-6.jpg", "img/b/sbsocial-7.jpg", "img/b/sbsocial-8.jpg", "img/b/sbsocial-9.jpg", "img/b/sbsocial-10.jpg", "img/b/sbsocial-11.jpg", "img/b/sbsocial-12.jpg", "img/b/sbsocial-13.jpg", "img/b/sbsocial-14.jpg", "img/b/sbsocial-15.jpg"],
    text: { pt: "Criação de peças para as redes sociais da Sportsbet.io Brasil: Instagram, Twitter e Twitch.", en: "Social media visuals for Sportsbet.io Brazil: Instagram, Twitter and Twitch." } },
  { via: "Warner Bros.", client: "TNT Sports", cover: "img/b/tnt-24.jpg", images: ["img/b/tnt-2.jpg", "img/b/tnt-3.jpg", "img/b/tnt-4.jpg", "img/b/tnt-5.jpg", "img/b/tnt-6.jpg", "img/b/tnt-7.jpg", "img/b/tnt-8.jpg", "img/b/tnt-9.jpg", "img/b/tnt-10.jpg", "img/b/tnt-11.jpg", "img/b/tnt-12.jpg", "img/b/tnt-13.jpg", "img/b/tnt-14.jpg", "img/b/tnt-15.jpg", "img/b/tnt-16.jpg", "img/b/tnt-17.jpg", "img/b/tnt-18.jpg", "img/b/tnt-19.jpg", "img/b/tnt-20.jpg", "img/b/tnt-21.jpg", "img/b/tnt-22.jpg", "img/b/tnt-23.jpg", "img/b/tnt-24.jpg", "img/b/tnt-25.jpg", "img/b/tnt-26.jpg", "img/b/tnt-27.jpg", "img/b/tnt-28.jpg", "img/b/tnt-29.jpg", "img/b/tnt-30.jpg", "img/b/tnt-31.jpg", "img/b/tnt-32.jpg", "img/b/tnt-33.jpg", "img/b/tnt-34.jpg", "img/b/tnt-35.jpg", "img/b/tnt-36.jpg", "img/b/tnt-37.jpg", "img/b/tnt-38.jpg", "img/b/tnt-39.jpg", "img/b/tnt-40.jpg", "img/b/tnt-41.jpg", "img/b/tnt-42.jpg", "img/b/tnt-43.jpg", "img/b/tnt-44.jpg", "img/b/tnt-45.jpg"],
    text: { pt: "Criação de posts para as redes sociais da TNT Sports Brasil (Instagram e Twitter).", en: "Social media posts for TNT Sports Brazil (Instagram and Twitter)." } },
  { via: "Sportsbet.io", client: "Copa do Brasil", cover: "img/b/cdb-7.jpg", images: ["img/b/cdb-1.jpg", "img/b/cdb-2.jpg", "img/b/cdb-3.jpg", "img/b/cdb-4.jpg", "img/b/cdb-5.jpg", "img/b/cdb-6.jpg", "img/b/cdb-7.jpg", "img/b/cdb-8.jpg"],
    text: { pt: "Peças para a Sportsbet.io como patrocinadora oficial da Copa do Brasil: promoções, odds da final e conteúdos da competição.", en: "Visuals for Sportsbet.io as official sponsor of the Copa do Brasil: promotions, final odds and competition content." } },
  { via: "Copa do Brasil", client: "Collab Flamengo", images: ["img/b/collab-flamengo-1.jpg"],
    text: { pt: "Peças para a collab da Copa Betano do Brasil com o Flamengo.", en: "Visuals for the Copa Betano do Brasil collab with Flamengo." } },
  { via: "Projeto autoral", client: "@dianalopesart", images: [],
    text: { pt: "Criações autorais publicadas no meu Instagram, @dianalopesart.", en: "Personal work published on my Instagram, @dianalopesart." } }
];
